// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "quran": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/ccdatatraits/quran/design
// --out=$(GOPATH)/src/github.com/ccdatatraits/quran
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
	"strconv"
)

// ShowQuranContext provides the quran show action context.
type ShowQuranContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	AyaID  int
	SuraID int
}

// NewShowQuranContext parses the incoming request URL and body, performs validations and creates the
// context used by the quran controller show action.
func NewShowQuranContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowQuranContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowQuranContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramAyaID := req.Params["ayaID"]
	if len(paramAyaID) > 0 {
		rawAyaID := paramAyaID[0]
		if ayaID, err2 := strconv.Atoi(rawAyaID); err2 == nil {
			rctx.AyaID = ayaID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("ayaID", rawAyaID, "integer"))
		}
	}
	paramSuraID := req.Params["suraID"]
	if len(paramSuraID) > 0 {
		rawSuraID := paramSuraID[0]
		if suraID, err2 := strconv.Atoi(rawSuraID); err2 == nil {
			rctx.SuraID = suraID
		} else {
			err = goa.MergeErrors(err, goa.InvalidParamTypeError("suraID", rawSuraID, "integer"))
		}
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowQuranContext) OK(r *Quran) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.quran+json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// NotFound sends a HTTP response with status code 404.
func (ctx *ShowQuranContext) NotFound() error {
	ctx.ResponseData.WriteHeader(404)
	return nil
}
