// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "quran": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/ccdatatraits/quran/design
// --out=$(GOPATH)/src/github.com/ccdatatraits/quran
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// QuranHref returns the resource href.
func QuranHref(suraID, ayaID interface{}) string {
	paramsuraID := strings.TrimLeftFunc(fmt.Sprintf("%v", suraID), func(r rune) bool { return r == '/' })
	paramayaID := strings.TrimLeftFunc(fmt.Sprintf("%v", ayaID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/quran/%v/%v", paramsuraID, paramayaID)
}
