// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "quran": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/ccdatatraits/quran/design
// --out=$(GOPATH)/src/github.com/ccdatatraits/quran
// --version=v1.2.0-dirty

package app

import (
	"github.com/goadesign/goa"
)

// Information from Quran (default view)
//
// Identifier: application/vnd.quran+json; view=default
type Quran struct {
	// aya # within sura
	Aya *int `form:"aya,omitempty" json:"aya,omitempty" xml:"aya,omitempty"`
	// API href for making requests to the aya
	Href string `form:"href" json:"href" xml:"href"`
	// index to each aya
	Index int `form:"index" json:"index" xml:"index"`
	// sura #
	Sura *int `form:"sura,omitempty" json:"sura,omitempty" xml:"sura,omitempty"`
	// Arabic text
	Text string `form:"text" json:"text" xml:"text"`
}

// Validate validates the Quran media type instance.
func (mt *Quran) Validate() (err error) {

	if mt.Href == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "href"))
	}
	if mt.Text == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "text"))
	}
	return
}
