// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "quran": Application Security
//
// Command:
// $ goagen
// --design=github.com/ccdatatraits/quran/design
// --out=$(GOPATH)/src/github.com/ccdatatraits/quran
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

type (
	// Private type used to store auth handler info in request context
	authMiddlewareKey string
)

// UseOAuth2Middleware mounts the OAuth2 auth middleware onto the service.
func UseOAuth2Middleware(service *goa.Service, middleware goa.Middleware) {
	service.Context = context.WithValue(service.Context, authMiddlewareKey("OAuth2"), middleware)
}

// NewOAuth2Security creates a OAuth2 security definition.
func NewOAuth2Security() *goa.OAuth2Security {
	def := goa.OAuth2Security{
		Flow:             "accessCode",
		TokenURL:         "http://localhost:8888/token",
		AuthorizationURL: "http://localhost:8888/authorization",
		Scopes: map[string]string{
			"api:read": "Provides read access",
		}}
	def.Description = "Use OAuth2 to authenticate"
	return &def
}

// handleSecurity creates a handler that runs the auth middleware for the security scheme.
func handleSecurity(schemeName string, h goa.Handler, scopes ...string) goa.Handler {
	return func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		scheme := ctx.Value(authMiddlewareKey(schemeName))
		am, ok := scheme.(goa.Middleware)
		if !ok {
			return goa.NoAuthMiddleware(schemeName)
		}
		ctx = goa.WithRequiredScopes(ctx, scopes)
		return am(h)(ctx, rw, req)
	}
}
