// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "quran": Application User Types
//
// Command:
// $ goagen
// --design=github.com/ccdatatraits/quran/design
// --out=$(GOPATH)/src/github.com/ccdatatraits/quran
// --version=v1.2.0-dirty

package app
